Register presets
chipsalliance/treadle pull request #331
Opened 2021-05-28 22:18 UTC by chick

Evaluation support is a bit primitive.
When registers with async reset types are
matched with a RegisterPresetAnnoation then the
raw datastore is initialized with the literal
reset value.

2021-06-03 00:19 UTC, ekiwi requested changes
Instead of using the `PresetAnnotation` it would probably be much easier to use the `PresetRegAnnotation` annotation. The way this works is that the `PropagatePresetAnnotations` pass analyzes all reset signals and `PresetAnnotation`s and then it annotates all registers _directly_ with a `PresetRegAnnotation`. Maybe we will have to make that public for treadle to be able to access it. But I believe this will vastly simply your implementation since you are essentially re-implementing the `PropagatePresetAnnotations` apss.

2021-06-03 00:19 UTC, ekiwi commented on src/main/scala/treadle/executable/ExpressionCompiler.scala
> +  private val presetTargetList = presetTargets.map { presetTarget =>
We should add something like this to `firrtl`. I feel like I have written similar code before.
@seldridge @jackkoenig , do you know if there is already a way to turn a reference target into a path string?

2021-06-03 00:19 UTC, ekiwi commented on src/main/scala/treadle/executable/ExpressionCompiler.scala
>    def getWidth(expression: Expression): Int = {
FYI, I think there is already a `firrtl.bitWidth` function that may do the same thing.

2021-06-03 00:19 UTC, ekiwi commented on src/main/scala/treadle/executable/Symbol.scala
> +    val refString = referenceTarget.ref
what is the purpose of `refString`?

2021-06-03 00:26 UTC, ekiwi commented
This is now blocked on: https://github.com/chipsalliance/firrtl/pull/2254

2021-06-09 19:39 UTC, chick commented
Closing this. Similar code was inadvertently pushed direct to master. By time it was discovered other changes had gone through. This will be cleaned up in next round of changes related to "Preset" changes

2021-06-09 19:39 UTC, closed without merging